### ISSUE TITLE
Support multiple users per client

### ISSUE THREAD

**Issue by molip** [molip/Eclipsoid#28]
We need to support multiple users logged in on the same client (e.g. in different tabs).

This requires: 
- [x] Multiple session cookies
- [x] A way to get to the login page when a user is already logged in
- [x] A way to switch users
